### ISSUE TITLE
No definition for wcf_filename in 1-genSuncgDataset/selectroom.m

### ISSUE THREAD

**Issue by cchiesa** [ManyiLi12345/GRAINS#7]
We are looking to utilize to this on a dataset but we get an error when trying to parse the rooms. 
Could you please update the readme to state what is needed for that matrix.

**Comment by ManyiLi12345** [comment]
We have added an update and provided the data format definition with a visualization script for the room_wcf file. Please check the update [here](https://github.com/ManyiLi12345/GRAINS/blob/master/README.md#update-because-of-the-suncg-dataset-problem-we-have-removed-the-pretraned-models-and-the-room_wcf-data-file-here-we-provide-the-data-format-definition-for-the-room_wcf-file-used-in-our-code-and-a-sample-file-which-can-be-visualized-with-this-script-please-follow-this-format-to-create-your-own-room_wcf-file-from-other-indoor-scene-dataset-to-use-our-code). Thanks for pointing it out.
